on: "3.8"

services:
  django:
    build: .
    container_name: sd
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    image: aldo564/sistemas_distribuidos:latest
    depends_on:
      - mongodb
    networks:
      - neows-network
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: neows
    ports:
      - 27017:27017
    networks:
      - neows-network

networks:
  neows-network:
    driver: bridge